api_key: ENC[AES256_GCM,data:ycSNbfPLm/dqBAV00kZaaBlfhwcdizJjhB8DYh40QNt2kGN4Igf8bA==,iv:C4kZMmNPG3teJgLWcwqh2uC+ljD/afxlRn97S8YwygM=,tag:1siZRbQ+YmcGzw3UomlFIA==,type:str]
zone: ENC[AES256_GCM,data:8GOMU8V2ofDW/Pnuog==,iv:+vXMjDvL7hx6WXI0eDo58PytK9H4vPWXFer1P8INwBI=,tag:UWNzt2Cnr1d50/adrDbxxA==,type:str]
subdomain: ENC[AES256_GCM,data:GwIn,iv:7PaiMPAY3MUFo/ybdyZ9EJ1LIssHk9woPkBQwvle7qc=,tag:Wu4EFhFHvRvtZq7jKGmFQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-27T07:52:16Z'
    mac: ENC[AES256_GCM,data:9OaDOQr5YJiWPmUgUS/GzGXdw3QHRKWpmNkH/LCuLCaENpXc3gk+xebz6aTiaXIqwTQlGpSc9RkFoV1j7BZuf/HiQrDL1eO0NQ9e7sBDT0JuhC7ZayD4HOSRVcuNabZdUSKyau0KqGnFGV2dwh7WieTgeYwLiqNk1q6yoF9Opr0=,iv:nMqVbZf/fMpirIsaQqByiGr+gHvcvQ8z0upctf7uNDk=,tag:UpSrgSp20n76i5bRLZMAnQ==,type:str]
    pgp:
    -   created_at: '2020-10-27T07:50:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/4sc6bB32aWAQv6A2WWKSUZ4iBRs3gFhE6nDV3LAD7dc9EOZEsJcctjzNoJ
            ydtcYhzhW0URObb7ir5akBQab2X/Vc9DxQBMA2GocoWI/shV9noJJsoPLbo3xAIN
            Zz2/dPbABPgXNOpeZ6e7xcKXIqg/bGSL2HPTX46EZn9Sisct7O78/eh5yr4n6v8G
            TttcOmpjViMdDm3OZ3zjh+3BfkNiN3s477iS46nu90/jd7T4PGxmHuPG5nramsN8
            1nx/XlVILsaZr5il5NqEG0lwZyP05PcmiNC/ds+kI0wsuXkzucSU2t8wFDAvOUt/
            w3bFv/7Vi8h/W7ut9zsAiR5TN9A7tcKFck7SFl14j3pqunBMn/gLJItpR0st5Hae
            K+IL83FQke7hDhZjeP8gRqgU/RRfX6MM1GFWPX7dkUBvsRRUxWLLCSacfjhGJ27f
            7zjTW6DUYS4eQ7GEhFNvMhQD/NKfdpJ98d74ZibY/dlOfZqk7dNANDU7kcTTe0kO
            7teaaIUlqEH75xURCpyI0l4Bm722ltUv1773mcXgPi5nzpO4EOkhctIDk6xZuRKb
            J69jDlMou9ZhQJtctxSTvkHpu9FXdwJGeB+WBKKx70s+MqxuVEHQkvJKuX7b0gwg
            HXOCpIdYrClacyxDhosN
            =TKIP
            -----END PGP MESSAGE-----
        fp: 42FC69294509367FA7A75C746C5CC1225E6B48CF
    unencrypted_suffix: _unencrypted
    version: 3.6.1
