config:
    domain: ENC[AES256_GCM,data:s73ijnUwoS+NfdjZOeVk39w=,iv:xQhxuYcGgww6NKL8ZAJ86OnDF0I+c76boJduycQwCmk=,tag:M7pbNLc0Z11pPHDRFzOfMw==,type:str]
    ip: ENC[AES256_GCM,data:R79WcMdETdc=,iv:FJzq2wyTkuQlC6tP1GP+3AmbA4/AFrcEq8/K4pNVlbs=,tag:ngD+8wkaZejeoA0QDhWELQ==,type:str]
    datadog:
        api_key: ENC[AES256_GCM,data:lQFjQ5kZTui1fuXj3GQRTqklJchsvpBCj0ABbA0V/Gk=,iv:eh7LjAuzGjoa2CyXMFQnfK71GPv4yfjHit9hDejc0ow=,tag:k+AYoLFCk+SgmZMrUfx6Vw==,type:str]
        dashboard_url: ENC[AES256_GCM,data:zR+f5sidX6b2L6jC8/xjlREre5XKLZ1r5geJsVHgEnEFmuir4bp9eKn6LeccjbosztHv30GxbbLTIA==,iv:f//NyGqHItzTb/Y/KRU8mnFXI/aUouqkABA3S/+Th/k=,tag:WyHoJO046yep/rLhQVb5Pg==,type:str]
    cloudflare:
        api_key: ENC[AES256_GCM,data:dSql54O7jXhX/HXUAObswNDunwoDStivap8jVQHZIjzEbSeyYqnMWw==,iv:XuJHIzj4p7q10t6YFtiqmoXDaPW0zZjP5D/g5pIxqHY=,tag:QNeh9CDHU9EZ1tk0Gg/9Qw==,type:str]
        zone: ENC[AES256_GCM,data:b44wi/ft0/0vC3wrxQ==,iv:khd7ar8AN+ntWUd/NMSGNA0EYV52JjHSoTBO3u9xuGE=,tag:rQTYNp5t1EgOr48xBaMl7A==,type:str]
        subdomain: ENC[AES256_GCM,data:/Cf6,iv:6Z6yrz+upvtRyPrX8ZtjR4zWRiqGutzreALS0gPMoaw=,tag:nnclMY3YuhscA7iirdmHjw==,type:str]
    paper:
        ip: ENC[AES256_GCM,data:ls9+17e2FOM=,iv:79+gY7+8UT9M1ASAE99K0v23CvzYhaLE9w7vGtWtTYg=,tag:aUZLw0mol2EFryTq1FNETQ==,type:str]
    pi_hole:
        adlists:
            - ENC[AES256_GCM,data:GJ8L58TUY0bCbTOHVuPQtJGIAbgdFwDV39gUOi28yZBXJqEGmLKtyaT5q9TScsCFuM7aS1TGoSPyfD407VTjE5XOyOntO1rfr3XgIxxOuCYXsO6+V7t7ehsLN9Td4dEX3Ts=,iv:mHoHQqQ31BOSJFPrX8DXUWCKwtJukov9MWeSVs4fr6Y=,tag:LRRKWIjn2ljt64JMen52tg==,type:str]
            - ENC[AES256_GCM,data:r4xtI3HNoi2d5vBSBWIiWZ+bskDMdtQBKhmnyclC3O/NZFwJHGx6U6EkqNY+v47RSRUJxn81jVBkErLjbd+dvv9uJeOasShrokEFgkMpJSLxMcyLUjhD1XTHTv8vlwlobnzt13HAcALpi1KNIS8=,iv:iIcg0+QpYwhI+yGYCFcxRiuFjeB2Q+ebwxtc4IVfHyM=,tag:qwrJCh3JCK9yPSzE5ingmA==,type:str]
    light:
        ip_address: ENC[AES256_GCM,data:0g3MOBJ2ggjTZs2zfg==,iv:q7LZOkQOBoKtLRobAddsphqIehaIPr3fjctyR20zA4E=,tag:T3/CssXfbqhAV9kFbRUyOQ==,type:str]
        child_id: ENC[AES256_GCM,data:s1cTKZaOWapsngq3An9fvmUnV+LaC7HBcdS/MOdHCzjBNIRXki61/w==,iv:jZwhPgRl8sSniYVDF/pOnzhvs3H7agFOmO3VbqWNXpY=,tag:AXaxBunIGAGQ43svG2pAjw==,type:str]
        puck_mac_addresses:
            - ENC[AES256_GCM,data:Y3c+p906iKjOoOToZgbUV3Q=,iv:ZC7YATm22mQPfO0W9e1yqEXiVV8vLjsti0TcU+3lcD0=,tag:Qu4QpqCSCeKBYpqPGaPNmA==,type:str]
            - ENC[AES256_GCM,data:17ES7RBxalG+Wj85k2FxX1U=,iv:SrOJzLhBCvtSNI/rldVt8HDsupG9r5DUFsFpEvzJ3Os=,tag:YES9B2ijkF3oCE29o8OaNw==,type:str]
    wireless_ap:
        address: ENC[AES256_GCM,data:tYyAbbr0kUrSVjG61i0=,iv:5mdVj+nIAD+VkEthPOUrwmdJbJjsjKACzv5PB5xisbs=,tag:6gngiXelV5CTFaMJm1LfZw==,type:str]
        network: ENC[AES256_GCM,data:trypH/9++5z8KChJHIA=,iv:nWoZIrGcedVaHerTm5DO4MnUj+gSunL3ZIvaX4NENs4=,tag:DIT2loZiWUKBtQRA8jD00w==,type:str]
        dns: ENC[AES256_GCM,data:L5rL7psfHg==,iv:tYxWNNzj0pQuSF+XZIQOnzgsuvu4pA2BL5prpj9mGRc=,tag:PaqUI4kEBfOjbbk9SKm9MA==,type:str]
        static_leases:
            - mac_address: ENC[AES256_GCM,data:Y/oYTFPSPZFvlSy0dRzJt98=,iv:KLmLtxcRkKSAB/eLHsw+/xhvzwBCDlP5c+qscii4Smk=,tag:GHwX09+YXjWcaN/7IwDIKg==,type:str]
              address: ENC[AES256_GCM,data:S01kKbEBFAzysp1JIA==,iv:1Npb4Uy3RqV9OQhTZ1YRfMbzIqlfivAI2wIobx2yUjM=,tag:nNNIZ6vdurRuaf3eilrSRQ==,type:str]
            - mac_address: ENC[AES256_GCM,data:+cKJZMP9kqoS2KehND1ycm4=,iv:b7QMm7vAETWPMwqZ1SEbqpCylGsaXeT9fAd68RbFF4s=,tag:RXQxGkxkA0D56rn55pHpQg==,type:str]
              address: ENC[AES256_GCM,data:eAClqjsd0/EsyoV0,iv:wWp9QziygtXXD+JV/SmBWZmQNd5ogKBNA6skWPk4znI=,tag:JFqk35NGsl3G4bn1AXORFQ==,type:str]
        gateway_ssid: ENC[AES256_GCM,data:+Vb468f3QA==,iv:d3TiKFLCQ7P+nLsKdc02dNCTHnWruozUFX8s0NSqqJg=,tag:8FVWfmQVp86587lOpwfEPA==,type:str]
        country_code: ENC[AES256_GCM,data:r0w=,iv:H+XY1ubL4xGxXou1eUH/bSJEsoEtOiLUe5G3CT2Io4E=,tag:gnx57g3+eQybq1EuGbErlA==,type:str]
        ssid: ENC[AES256_GCM,data:wkllCvdFbqEH,iv:+Fo5Tub7uB+4ziCZWrfgsLrw+d0BxLu1glj6Tcz3s4M=,tag:bvl+ry89wy0eymvn7ZO6jg==,type:str]
        hw_mode: ENC[AES256_GCM,data:xg==,iv:ecf35xfHjprN4cZWG/Ze+PJcgBwzmHJLQoQ6urQS0E0=,tag:XqwsTWtqdpKkfr+NqagI2g==,type:str]
        channel: ENC[AES256_GCM,data:bg==,iv:CKcuOnLp/tToVHXeASpAYvRNx9XOcFBV5VjKkBsB9yY=,tag:XihpA6Li5ErsH8GaaPOjlQ==,type:int]
        wpa_passphrase: ENC[AES256_GCM,data:74ItH6ebgCZ0,iv:jW2G1UatoAbeDzgx9ANPHiTviJG5TvR+sTqX85ShrNc=,tag:vov69AY4jTJw9DfGcTVp2Q==,type:str]
    vpn_ui:
        session_secret: ENC[AES256_GCM,data:vuQySGyBWOjVUxEF2Bs3ZPSyTJe4LnX1jCS/MjM0vRESYsQVJ6YX2+aB,iv:kQz/IFGivQIGTvghKATZG58HYdJa4zznqcR4LyeaHYE=,tag:4FW03zIuG2im25+YV9JXbg==,type:str]
        subnet_ranges: ENC[AES256_GCM,data:QzRA1IR0HtyBRPAslUhX,iv:Pin9u0IUe9r4IeN8SV04QEO3pV8ApT2MY4aC2rI4DFQ=,tag:aqlNtZw3lgFO99XhQSfhUA==,type:str]
        default_client_allowed_ips: ENC[AES256_GCM,data:/T/ws7t269y0btE=,iv:lZm+cFt1nqVvq3R0vpbab9b1BD9cghjeYu1letG/+0U=,tag:uGPgDxrOXD5PIC3BgfUIFQ==,type:str]
        firewall_mark: ENC[AES256_GCM,data:cldx+dBP,iv:ph+xyV33KMLC9lGc8iWc+PyGm3UPyi+sB/IEiBQKLxw=,tag:nIknR48FPOh8ClvBIkQJ5A==,type:str]
        server_listen_port: ENC[AES256_GCM,data:aBnKDnA=,iv:ZzqWIDKyx/yZq7G/GFzWqyjYU345eZ8RigG08UDKVQ4=,tag:cPGvNyEAfITX0leuoS8J4g==,type:str]
    temporal:
        postgres_password: ENC[AES256_GCM,data:UKNS+yKpY5/eopq1lc1GOMGAR8pX,iv:Hhx9Npgl+6r9MYBnSCbO7IjFHdpGt3imYN8R88C46KI=,tag:8KJQG/RoHRRmJSU8Z1E72g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-03T22:53:43Z"
    mac: ENC[AES256_GCM,data:PX5VGA1t31ORLlj+ZxDg8LckmXJX4GziOb+k0Y9fsK9YOyDs5JQwNgeTWInlGeiGlK+wNzVF41uQJFn50taMzlHzycT+o2gJgJ3JNxc5numNJjISP31s1VBLMUvApfZaxbm8d2bn5EB1wUiZE/+0rWkLRH42NZJik6JygEcVxUI=,iv:+ZeuDLkyorLmlWUNeMymO8FQ7Gx9SVOqC0lt+UnFV30=,tag:AGs8AAsRSAoZ01as67c79g==,type:str]
    pgp:
        - created_at: "2021-12-27T08:11:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/4sc6bB32aWAQv+PNh9Rz5gRLdC8kpUPwo8lTFIBFvk4quEYaShxrs9+i8b
            XHU84MEGIRdrtijpp6vD0zonEIT+HW62UPNEZXwTHhZJDMFsXVAVbGHnVh2Shw0w
            1qI+72nGZEl7EIEsVDItNiAp+ISNUaTDy3tHYgXPASEcp0EFPiiIkou0b4Hi7OPy
            rs8gboHxmWdQkSSc+1LyKroRKhxOxABl2QLO2IXTPYXx5mk3yUkf99h1E5463r9b
            +Wbm7ZsIeRBIgXAPQ6KhD6tn8lLsJpJkbA7J7qP+MqX0XzgnlfxBD0n9/sdxZtFl
            k9uXyhSpxVPvBLyoVdCh1fuyCmkbsC6fSHCEquDyyLPtgQO1eC0VPNrDxZTRM/Mo
            nZo2W7oZpRKfJoPu2COTR6ISq6rSnGL0H4VZv/k1+HrkyZGHopRAfCwcWY9ETswQ
            9/vQG8ly9/3sF0EdP6M5RbO9IBLIuBAIvqT/sMabmWaHRpIZFyle4FMCsCrRWzwE
            72PeknSAdBowSLcyRgTz0lwBAyZ6tmuUBkXScAlSC957Gj2Z7IDmXJybRd99WlA1
            Gkzo6B/0ZVhR5Emv2Wc0+5I4UJFt2qV9Sz+/ny+j674g4YPUZXvtgqA9z7UrZrRm
            D6QC61XZwrIsxOBVWg==
            =e3st
            -----END PGP MESSAGE-----
          fp: 42FC69294509367FA7A75C746C5CC1225E6B48CF
    unencrypted_suffix: _unencrypted
    version: 3.9.1
