apiVersion: ENC[AES256_GCM,data:Ao8=,iv:XfJQLKduMGGnIDJFOGHj4IRBaU2F2JMPbkNuelYYuT0=,tag:cEk8hh+0yGn1rgvIw1RSIg==,type:str]
clusters:
-   cluster:
        certificate-authority-data: ENC[AES256_GCM,data:bC2qFvCQKDFUsEE2DDPqPSksW5JLI2K6yD7I0OUJwNN5LkeAL97qtfKWoMp+fUMO2x+vdfH1PBZ8yfRX/Dzzif/LeTnXW8gqEe7X+3D4HVvbd1mjIemq1zUi4QmbT5zWdD5emq3hrvofGQ128hV/b3csGNPUgcsRbjXfBmGiTAuJGfGrlsGWLXvO1sXC29vcNtX5yCf55OPZdCKMi70aCPHHcjxjQOrC9qsg3ZflNUOTZRq8+j6cf1LqWP3nYo2jHRIin3NppuKCnnFZh8DwEy8r39Af+J1Vyq77kDh3NAtxLh/kcBQCq0FRB31tJw2cgT2+FREYM6Hrv82F2T8ydJCby1aRd45ca+OBXD5as6kclWSgjFSkxJm1L5Yz4s+CfsWK0oh0USXxZXjF9Lz2NqsBfsxB4lV5ZhLPo8VKQf7dYTIKG+fb1vX+Pwu3sRsywKvvRJ+o/OwxqgjQmgcM9vFkYjIwNX5MyxIfEWSQYLTfvWJCRQVZBNaf9mvNGB4tA2Jcfc5Pzi06e2AolPZcTriNTkZ8v7LJovKI84NUE0LW8Y6NQTJ4yYRi2w9NXw/lum47iJVTHCxhUJ5op3OW82z5SvoRZqqUDgopA9nWNEoHr9snKdF/fTy/IcqCJUvFYQgMaEU5ci755KX3vKEE10O2lpMzyWcgn9TRjYymB5PdcAn+q+6bvJ1BSMrAcqIZ37KAKGirtD5a8FpKW0cqZ4FNBr+L3FMj6wauU5en9UBNkFeENPCWPzKmbmoV8yOBtbwg7zFOkwLvB1aMDUBIdN5EIeSRh7G0nrVQlrZEOX2q4l1ysfUh+vaIGTqH+1ZhEhd5P+lE1GQKs4N0eoOMnAFlu5PGI0EOrNhW7D3HK/fvQteRBZiN3+Q0iT6yHambzAgxdTzMxmc6StwJgKDlPJykxpEBlF9anwRNHAyMlQo=,iv:A61GdMyQj5zB1hjVy01cY5U/LP7n17v/ADWpHoZAy2A=,tag:9fCFxLXFSFmoFn6n1En9xA==,type:str]
        server: ENC[AES256_GCM,data:ML0tQ+VAgjzpdj4MPWwwOEbDjNvG,iv:Gx6oaDtJrwS14xI3OdtqOomlcQSDWa5bJ+gGck6PXaI=,tag:ImeKpol6slBOwuU4SDetWg==,type:str]
    name: ENC[AES256_GCM,data:BqZUhJ3fiQ==,iv:gOWlZaV3GUpYxcS5B8Shrg6D2qjqTZcj+NCojxUDmIk=,tag:DnilPsuj+YLdz5y8ej3C6g==,type:str]
contexts:
-   context:
        cluster: ENC[AES256_GCM,data:5Hii0/jIsw==,iv:M/2HeDPcKFRpVARpd6gcKYQxzhf4Zd4KFrx3GqiEuJo=,tag:4s7SPiG77/CfbrC1Mb/CVA==,type:str]
        user: ENC[AES256_GCM,data:+viELVJ8Gw==,iv:qZQL6D2e3p39ex5vnWScs07EuGoVan/x00EKKOdxbis=,tag:OAWTCOoD8d3Wew9aLC7cMw==,type:str]
    name: ENC[AES256_GCM,data:vR5/B1k8CQ==,iv:gFkdBI/mFYbx4brhCAYgOKmlKUaQ4F0KaG/aBhZlgc0=,tag:J8gWeqzXy8bJVfNApwP3vg==,type:str]
current-context: ENC[AES256_GCM,data:P5d34YTvZw==,iv:lKE9ZbRJjTalNyJHH7A51ToakwMmSL6YZubJsoATmOQ=,tag:HmeSPMxt6XHY9Aj7YbEE7g==,type:str]
kind: ENC[AES256_GCM,data:sCtghhxa,iv:sDxckt3Y/z59t814axe7e9ZE9kwf5VDuerr5R1lTZ3E=,tag:cF8H9Vur8eQ71HvPpu5c4w==,type:str]
preferences: {}
users:
-   name: ENC[AES256_GCM,data:8mAl7/0vtw==,iv:29C0x9xKtZwyCPcy8HIL3b5KGDpWnlcgc1dyzNLr2Yc=,tag:eTSRNmmmHPgvkd9aQvdJlQ==,type:str]
    user:
        password: ENC[AES256_GCM,data:v5uhJ0y7jb5d5cgptvHGA/HZwHqCAdKbmFwb/dIT3H8=,iv:6tVsBZVDi+Ukf3oM72na5p5XZ1lcpLLGdwurvbuVPaA=,tag:bkA9/luicex1b6PDZkQR4A==,type:str]
        username: ENC[AES256_GCM,data:37BkmCU=,iv:UMflJ4BmmTY0mxsjzUmkib/GXtlHtrRn2JLmIsAxbNw=,tag:UBPiXjBLJNoL6qG1ZplQSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-13T10:21:45Z'
    mac: ENC[AES256_GCM,data:Q6KdydWcYn00xb7dPPHkPlghLUI3y2g2xnovt4fQYkMcluUvUrOfwMGb5aeOcVZQTfeEzOytz/7AffNEhEDQfgBJ+tUjNWvowX6tNMEelPABCNg7gFKaNJK5mFsvlIDWSSYK9Or9HDJYt2ovSWtyw924IyytYVVZ78fzgTzHgdQ=,iv:hatV4p+9JGOGJ6Lp8xfC6Fho1UiLorzVAVxgvtzKqKE=,tag:MTn+q9yzB7GL1nIp1GxhNA==,type:str]
    pgp:
    -   created_at: '2020-10-13T10:21:24Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/4sc6bB32aWAQv6A0xuQgUE7Mw4he18XEG4zSanAjJj7to2Eyc9r21l8MV6
            JK4AZlKT93CExGks+CfRC9yNJXznAA/ldJaC71bPR8xuuITzZzxQywZmq6KY6g94
            GI3Xm8T4GF33YFs5iUacoN9U+T2ZosnUebLXvtjZ8gYyXzYgIhitwUEamDGHXuCC
            k9VPpMOEuIng/HSxoXYgKVxrsULDpn/2q/hrY3ofvYLPeD5/CqQ6Z0RC3bSJIMb0
            xd1dAKkEfpPxQh6R0zuiP5VFUg1DEevI1dqT9M0n5xCtxSxIQGYXuRUWVshbJk6l
            6VVlIZI/AU2+Q8AWsH+Vg8908iTyDecruT6O/UmC3BU0U8Ifw+8/QlFdRy/iyDyz
            sc/jXJaOzZ0IwRS3VXAq0dqfUohdwI2pRSsM8167Un1OqRccKO06UuEwsDx6mi7h
            drD7/GXVc+5ivEo1qO27S8Iqpc5qyK42yHrNm3jihJZo1D482gPBWF5dKA6N6F9+
            RmqgdXgfPCfeh8skHbC+0l4BvEVqrCqbxVDudz9gtiTHBpLAhxcmt7DwsygzXSek
            HO0UGC8Iv3qpREWAZQ6w/j50uvMJOqLQRfraZgu5eVetECgxaQAIOSECiibpBKug
            PJMB9XvqZid8Wrpe+Bzp
            =vzAq
            -----END PGP MESSAGE-----
        fp: 42FC69294509367FA7A75C746C5CC1225E6B48CF
    unencrypted_suffix: _unencrypted
    version: 3.6.1
