---

- name: set dns record
  community.general.cloudflare_dns:
    zone: "{{ config.cloudflare.zone }}"
    record: "ticker.{{ config.domain }}"
    type: A
    value: "{{ config.ip }}"
    api_token: "{{ config.cloudflare.api_key }}"
  delegate_to: localhost

- name: build
  community.docker.docker_image_build:
    name: "gitea.{{ config.domain }}/{{ config.gitea.username }}/ticker"
    tag: latest
    path: "{{ role_path }}"
    rebuild: always
    args:
      VITE_TICKER_USERS: "{{ config.ticker.users | to_json }}"
    platform:
      - linux/amd64
      - linux/arm64/v8
    outputs:
      - type: image
        push: true
  delegate_to: localhost
  register: build_result

- name: deploy stack
  community.general.docker_stack:
    name: ticker
    prune: yes
    resolve_image: always
    compose:
      - version: '3.8'
        services:
          ticker:
            image: "{{ build_result.image.RepoDigests[0] }}"
            networks:
              - traefik_traefik
            environment:
              DONETICK_API_KEY: "{{ config.ticker.donetick_api_key }}"
              DONETICK_URL: http://donetick_donetick:2021
              TZ: America/Los_Angeles
            deploy:
              mode: replicated
              replicas: 1
              labels:
                - "home.scheduler.replicas=1"
                - "home.scheduler.priority=50"
                - "home.scheduler.restart=true"
                - "traefik.enable=true"
                - "traefik.http.routers.ticker.rule=Host(`ticker.{{ config.domain }}`)"
                - "traefik.http.routers.ticker.middlewares=traefik-internal,traefik-forward-auth"
                - "traefik.http.routers.ticker.entrypoints=websecure"
                - "traefik.http.routers.ticker.tls.certresolver=letsencrypt"
                - "traefik.http.services.ticker.loadbalancer.server.port=80"
              resources:
                limits:
                  cpus: '0.15'
                  memory: 20M
              restart_policy:
                delay: 30s
              update_config:
                order: stop-first
        networks:
          traefik_traefik:
            external: true
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
