---

- name: install
  ansible.builtin.apt:
    name:
      - wireguard

- name: ipv4 forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes
  notify: vpn_restart

- name: ipv6 forward
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    state: present
    reload: yes
  notify: vpn_restart

- name: configure
  ansible.builtin.copy:
    content: "{{ lookup('community.sops.sops', 'pi-wg1.conf') }}"
    dest: /etc/wireguard/wg1.conf
    owner: root
    group: root
    mode: u=rw,g=,o=
  notify: vpn_restart

- name: enable service
  ansible.builtin.systemd:
    name: wg-quick@wg1.service
    enabled: true

