---

- name: restart nftables
  ansible.builtin.systemd:
    daemon_reload: true
    name: nftables.service
    state: restarted
  listen: vpn_restart
  when: vpn_ip_forward

- name: restart wireguard
  ansible.builtin.systemd:
    daemon_reload: true
    name: wg-quick@wg1.service
    state: restarted
  listen: vpn_restart

- name: restart wg1 timer
  ansible.builtin.systemd:
    daemon_reload: true
    name: wg1-restart.timer
    state: restarted
  listen: wg1_timer_restart
