---

- name: restart nftables
  ansible.builtin.systemd:
    daemon_reload: true
    name: nftables.service
    state: restarted
  listen: vpn_restart
  when: vpn_ip_forward

- name: restart wireguard
  ansible.builtin.systemd:
    daemon_reload: true
    name: wg-quick@wg1.service
    state: restarted
  listen: vpn_restart

- name: restart reresolve dns timer
  ansible.builtin.systemd:
    daemon_reload: true
    name: wg1-reresolve-dns.timer
    state: restarted
  listen: wg1_reresolve_dns_timer_restart

- name: restart restart timer
  ansible.builtin.systemd:
    daemon_reload: true
    name: wg1-restart.timer
    state: restarted
  listen: wg1_timer_restart

- name: restart sync path
  ansible.builtin.systemd:
    daemon_reload: true
    name: wg1-sync.path
    state: restarted
  listen: wg1_sync_restart
