---

- name: deploy docker secrets
  gather_facts: false
  hosts: pi
  tags:
    - traefik
  tasks:
    - name: traefik users
      community.general.docker_secret:
        name: traefik_users_secret
        data: "{{ lookup('community.sops.sops', '../traefik/users') }}"

    - name: cloudflare api key
      community.general.docker_secret:
        name: cloudflare_api_key_secret
        data: "{{ config.cloudflare.api_key }}"
