---

- name: deploy glances
  gather_facts: false
  hosts: pi
  tags:
    - glances
  tasks:
    - name: set dns record
      community.general.cloudflare_dns:
        zone: "{{ config.cloudflare.zone }}"
        record: "glances.{{ config.domain }}"
        type: A
        value: "{{ config.ip }}"
        api_token: "{{ config.cloudflare.api_key }}"
      delegate_to: localhost

    - name: deploy stack
      community.general.docker_stack:
        name: glances
        prune: yes
        resolve_image: always
        compose:
          - version: '3.8'
            services:
              glances:
                image: nicolargo/glances:latest-full
                labels:
                  - "traefik.enable=true"
                  - "traefik.http.routers.glances.rule=Host(`glances.{{ config.domain }}`)"
                  - "traefik.http.routers.glances.entrypoints=websecure"
                  - "traefik.http.routers.glances.tls.certresolver=letsencrypt"
                  - "traefik.http.services.glances.loadbalancer.server.port=61208"
                environment:
                  GLANCES_OPT: >
                    --time 10
                    --cached-time 5
                    --webserver
                    --disable-process
                    --disable-plugin fs,amps'
                volumes:
                  - /var/run/docker.sock:/var/run/docker.sock:ro
                networks:
                  - traefik_traefik
                logging:
                  driver: none
                deploy:
                  mode: replicated
                  replicas: 1
                  resources:
                    limits:
                      cpus: '0.50'
                      memory: 45M
                  restart_policy:
                    delay: 5m
            networks:
              traefik_traefik:
                external: true
