---

- name: deploy light
  gather_facts: false
  hosts: pi
  tags:
    - light
  tasks:
    - name: install
      ansible.builtin.apt:
        name:
          - libglib2.0-dev

    - name: create directory
      ansible.builtin.file:
        path: /home/pi/light-puck
        owner: pi
        group: pi
        state: directory

    - name: copy project files
      ansible.builtin.copy:
        src: "../light-puck/{{ item }}"
        dest: "/home/pi/light-puck/{{ item }}"
      loop:
        - pyproject.toml
        - poetry.toml
        - poetry.lock
      register: copy_project_files
      become_user: pi
      notify: restart

    - name: install dependencies
      ansible.builtin.shell:
        cmd: /home/pi/.local/bin/poetry install
        chdir: /home/pi/light-puck
      become_user: pi
      when: copy_project_files is changed

    - name: copy script
      ansible.builtin.copy:
        src: "../light-puck/{{ item }}"
        dest: "/home/pi/light-puck/{{ item }}"
      loop:
        - light.py
      become_user: pi
      tags:
        - light-script
      notify: restart

    - name: install service
      ansible.builtin.template:
        src: ../light-puck/light-puck.service
        dest: /etc/systemd/system
        owner: root
        group: root
      notify: restart

    - name: enable service
      ansible.builtin.systemd:
        name: light-puck
        enabled: true

  handlers:
    - name: restart service
      ansible.builtin.systemd:
        daemon_reload: true
        name: light-puck
        state: restarted
      listen: restart
