---

- name: deploy portainer
  gather_facts: false
  hosts: pi
  tags:
    - portainer
  tasks:
    - name: deploy stack
      community.general.docker_stack:
        name: portainer
        prune: yes
        resolve_image: always
        compose:
          - version: '3.2'
            services:
              agent:
                image: portainer/agent
                volumes:
                  - /var/run/docker.sock:/var/run/docker.sock
                  - /mnt/external/docker/volumes:/var/lib/docker/volumes
                networks:
                  - agent_network
                logging:
                  driver: none
                deploy:
                  mode: global
                  resources:
                    limits:
                      cpus: '0.50'
                      memory: 20M
                  restart_policy:
                    delay: 5m
                  placement:
                    constraints: [node.platform.os == linux]
              portainer:
                image: portainer/portainer-ce
                labels:
                  - "traefik.enable=true"
                  - "traefik.http.routers.portainer.rule=Host(`portainer.{{ config.domain }}`)"
                  - "traefik.http.routers.portainer.entrypoints=websecure"
                  - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
                  - "traefik.http.services.portainer.loadbalancer.server.port=9000"
                command: -H tcp://tasks.agent:9001 --tlsskipverify
                environment:
                  GOMAXPROCS: '1'
                ports:
                  - "8000:8000"
                volumes:
                  - portainer_data:/data
                networks:
                  - agent_network
                  - traefik_traefik
                logging:
                  driver: none
                deploy:
                  mode: replicated
                  replicas: 1
                  resources:
                    limits:
                      cpus: '0.50'
                      memory: 20M
                  restart_policy:
                    delay: 5m
                  placement:
                    constraints: [node.role == manager]
            networks:
              agent_network:
                driver: overlay
                attachable: true
              traefik_traefik:
                external: true
            volumes:
              portainer_data:
