---

- name: deploy registry
  gather_facts: false
  hosts: pi
  tags:
    - registry
  tasks:
    - name: set dns record
      community.general.cloudflare_dns:
        zone: "{{ config.cloudflare.zone }}"
        record: "registry.{{ config.domain }}"
        type: A
        value: "{{ config.ip }}"
        api_token: "{{ config.cloudflare.api_key }}"
      delegate_to: localhost

    - name: create directory
      ansible.builtin.file:
        path: /mnt/external/registry
        owner: root
        group: root
        state: directory

    - name: deploy task
      community.general.docker_stack:
        name: registry
        prune: yes
        resolve_image: always
        compose:
          - version: '3.8'
            services:
              registry:
                image: registry:2
                labels:
                  - "traefik.enable=true"
                  - "traefik.http.routers.registry.rule=Host(`registry.{{ config.domain }}`)"
                  - "traefik.http.routers.registry.entrypoints=websecure"
                  - "traefik.http.routers.registry.tls.certresolver=letsencrypt"
                  - "traefik.http.services.registry.loadbalancer.server.port=5000"
                volumes:
                  - /mnt/external/registry:/var/lib/registry
                networks:
                  - traefik_traefik
                logging:
                  driver: none
                deploy:
                  mode: replicated
                  replicas: 1
                  resources:
                    limits:
                      cpus: '0.25'
                      memory: 20M
                  restart_policy:
                    delay: 20s
                  update_config:
                    order: stop-first
            networks:
              traefik_traefik:
                external: true

    - name: wait for registry
      ansible.builtin.uri:
        method: GET
        url: "https://registry.{{ config.domain }}"
      register: result
      until: result is succeeded
      retries: 60
      delay: 5

