---

- name: setup
  gather_facts: false
  hosts: pi
  tags:
    - setup
  tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: check swap
      ansible.builtin.shell:
        cmd: cat /proc/swaps | tail -n +2
      changed_when: false
      register: swap_result
      tags:
        - swap

    - name: disable swap
      ansible.builtin.shell:
        cmd: "{{ item }}"
      loop:
        - dphys-swapfile swapoff
        - dphys-swapfile uninstall
      when: swap_result.stdout_lines|length > 0
      notify: reboot
      tags:
        - swap

    - name: configure journal
      community.general.ini_file:
        path: /etc/systemd/journald.conf
        section: Journal
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      loop:
        - option: Storage
          value: volatile
        - option: RuntimeMaxUse
          value: 15M
      notify: reboot
      tags:
        - journal

    - name: disable services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - dphys-swapfile
        - rsyslog
        - apt-daily.timer
        - apt-daily-upgrade.timer
      notify: reboot
      tags:
        - swap

    - name: enable cgroups features
      ansible.builtin.lineinfile:
        path: /boot/cmdline.txt
        backrefs: True
        regexp: '(^.+rootwait)$'
        line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
      notify: reboot
      tags:
        - cgroups

    - name: install
      ansible.builtin.apt:
        name:
          - vim
          - lsof
          - git
          - sysstat
          - python3-venv

    - name: install docker sdk
      ansible.builtin.pip:
        name:
          - docker
          - jsondiff
          - pyyaml

    - name: install pipx
      ansible.builtin.pip:
        executable: pip3
        name: pipx
        extra_args: --user
      become_user: pi

    - name: install poetry
      community.general.pipx:
        name: poetry
      become_user: pi

  handlers:
    - name: reboot
      ansible.builtin.reboot:
      listen: reboot
