---

- name: setup
  gather_facts: false
  hosts: pi
  tags:
    - setup
  tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: disable swap
      ansible.builtin.shell:
        cmd: "{{ item }}"
      loop:
        - dphys-swapfile swapoff
        - dphys-swapfile uninstall
      tags:
        - swap

    - ansible.builtin.systemd:
        name: dphys-swapfile
        state: stopped
        enabled: false
      tags:
        - swap

    - name: enable cgroups features
      ansible.builtin.lineinfile:
        path: /boot/cmdline.txt
        backrefs: True
        regexp: '(^.+rootwait)$'
        line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
      register: cgroups_result
      tags:
        - cgroups

    - name: reboot
      ansible.builtin.reboot:
      when: cgroups_result is changed
      tags:
        - cgroups

    - name: install
      ansible.builtin.apt:
        name:
          - vim
          - lsof
          - git
          - sysstat
          - python3-venv

    - name: install docker sdk
      ansible.builtin.pip:
        name:
          - docker
          - jsondiff
          - pyyaml

    - name: install pipx
      ansible.builtin.pip:
        executable: pip3
        name: pipx
        extra_args: --user
      become_user: pi

    - name: install poetry
      community.general.pipx:
        name: poetry
      become_user: pi

