---

- name: deploy vpn
  gather_facts: false
  hosts: pi
  tags:
    - vpn
  tasks:
    - name: install
      ansible.builtin.apt:
        name:
          - wireguard

    - name: ipv4 forward
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
      notify: restart

    - name: ipv6 forward
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '1'
        state: present
        reload: yes
      notify: restart

    - name: configure
      ansible.builtin.copy:
        content: "{{ lookup('community.sops.sops', '../vpn/pi-wg1.conf') }}"
        dest: /etc/wireguard/wg1.conf
        owner: root
        group: root
        mode: u=rw,g=,o=
      notify: restart

    - name: enable service
      ansible.builtin.systemd:
        name: wg-quick@wg1.service
        enabled: true

  handlers:
    - name: restart service
      ansible.builtin.systemd:
        daemon_reload: true
        name: wg-quick@wg1.service
        state: restarted
      listen: restart
