---

- name: create directories
  ansible.builtin.file:
    path: /etc/docker
    owner: root
    group: root
    state: directory

- name: configure
  ansible.builtin.template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
  notify: external_docker_reboot
